### ISSUE TITLE
torchvision version for CIFAR100

### ISSUE THREAD

**Issue by nlrahimi** [yaoyao-liu/class-incremental-learning#10]
Hi,

Thanks for your innovative method and sharing the code with community.
When running `python3 main.py --method=mnemonics --nb_cl=10` I face the following AttributeErorrs
`'CIFAR100' object has no attribute 'train_labels'` in mnemonics.py. This issue pesisted for train_data, as well and I was able to solve it by replacing `self.train` with `self.trainset.train_data`. 
However for:
- `self.trainset.train_labels`
- `self.testset.test_data`
- ` self.testset.test_labels`

no replacement worked with existing torchvision(0.5.0).
I would appreciate if you specify the torchvision that worked with your model.

Bests,
Nila

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

For the package version, please kindly refer to this issue: https://github.com/yaoyao-liu/mnemonics-training/issues/6#issuecomment-641219407

**Comment by nlrahimi** [comment]
This solved the error.

I would kindly recommend to add a requirements.txt file that contains all the packages with version mentioned in issue#6. When facing errors, many would search for errors in different website, under the impression that all the needed packages is already named in the page.

Thank you,
Bests

**Comment by yaoyao-liu** [comment]
Thanks for your suggestion.
We'll update the requirement list to this repo later.
